services: docker

matrix:
  include:
    - os: linux
      dist: xenial
    - os: windows
      dist: 1803-containers
      env: VERSION=1.11 VARIANT=windows/windowsservercore-1803


sudo: required

language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake3
      - libmongo-client-dev
      - libmongo-client0
      - libpq-dev
      - libpq5

install:

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - cmake -DNDB_ENGINE_SQLITE=ON -DNDB_ENGINE_POSTGRE=OFF -DNDB_BUILD_TEST=ON -DCMAKE_BUILD_TYPE=Release
  - make
  - make test