services: docker

matrix:
  include:

    - os: windows
      dist: 1803-containers
      env: VERSION=1.11 VARIANT=windows/windowsservercore-1803


sudo: required

language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libmongo-client-dev
      - libmongo-client0
      - libpq-dev
      - libpq5

  homebrew:
    packages:
      - postgresql


install:
  - if [ $TRAVIS_OS_NAME = windows ]; then choco install postgresql10 --force --params '/Password:ads'; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then pg_ctl -D /usr/local/var/postgres start; fi

script:
  - cmake -DCMAKE_C_COMPILER=${C_COMPILER} -DCMAKE_CXX_COMPILER=${CXX_COMPILER} -DNDB_ENGINE_SQLITE=ON -DNDB_ENGINE_POSTGRE=ON -DNDB_PQ_PATH="/c/Program Files/PostgreSQL/10" -DNDB_BUILD_TEST=ON -DCMAKE_BUILD_TYPE=Release
  - cat "C/Users/travis/build/ads00/ndb/CMakeFiles/CMakeOutput.log"
  - cmake --build . --config Release
  - ctest -C Release