services: docker
language: cpp
sudo: required

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - g++-8
      env:
        - C_COMPILER=gcc-8 CXX_COMPILER=g++-8

    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-8
          packages:
            - gcc-8
            - g++-8
            - clang-8
      env:
        - C_COMPILER=clang-8 CXX_COMPILER=clang++-8

    - os: windows
      dist: 1803-containers
      env: VERSION=1.11 VARIANT=windows/windowsservercore-1803
      install:
        - choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
        - choco install visualstudio2019buildtools --ignore-package-exit-codes --package-parameters '--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended --quiet --norestart'
        - choco install postgresql10 --force --params '/Password:ads'
        - mv "/c/Program Files/PostgreSQL/10/include/" "/c/Program Files/PostgreSQL/10/postgresql"; mkdir -p "/c/Program Files/PostgreSQL/10/include/postgresql"; mv "/c/Program Files/PostgreSQL/10/postgresql/" "/c/Program Files/PostgreSQL/10/include/"; dir "/c/Program Files/PostgreSQL/10/include/postgresql"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libmongo-client-dev
      - libmongo-client0
      - libpq-dev
      - libpq5

script:
  - cmake -DCMAKE_C_COMPILER=${C_COMPILER} -DCMAKE_CXX_COMPILER=${CXX_COMPILER} -DNDB_ENGINE_SQLITE=ON -DNDB_ENGINE_POSTGRE=ON -DNDB_PQ_PATH="/c/Program Files/PostgreSQL/10" -DNDB_BUILD_TEST=OFF -DNDB_BUILD_EXAMPLE=ON -DCMAKE_BUILD_TYPE=Release
  - cmake --build . --config Release
  - ctest -C Release