services: docker

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - g++-8
      env:
        - C_COMPILER=gcc-8 CXX_COMPILER=g++-8

    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-8
          packages:
            - gcc-8
            - g++-8
            - clang-8
      env:
        - C_COMPILER=clang-8 CXX_COMPILER=clang++-8

    - os: windows
      dist: 1803-containers
      env: VERSION=1.11 VARIANT=windows/windowsservercore-1803

    - os: osx
      osx_image: xcode10.1

sudo: required

language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libmongo-client-dev
      - libmongo-client0
      - libpq-dev
      - libpq5

  homebrew:
    packages:
      - postgresql


install:
  - if [ $TRAVIS_OS_NAME = windows ]; then choco install postgresql10 --force --params '/Password:ads'; fi
  - if [ $TRAVIS_OS_NAME = windows ]; then mv "/c/Program Files/PostgreSQL/10/include/" "/c/Program Files/PostgreSQL/10/postgresql"; mkdir -p "/c/Program Files/PostgreSQL/10/include/postgresql"; mv "/c/Program Files/PostgreSQL/10/postgresql/" "/c/Program Files/PostgreSQL/10/include/"; dir "/c/Program Files/PostgreSQL/10/include/postgresql"; fi

script:
  - cmake -DCMAKE_C_COMPILER=${C_COMPILER} -DCMAKE_CXX_COMPILER=${CXX_COMPILER} -DNDB_ENGINE_SQLITE=ON -DNDB_ENGINE_POSTGRE=ON -DNDB_PQ_PATH="/c/Program Files/PostgreSQL/10" -DNDB_BUILD_TEST=ON -DCMAKE_BUILD_TYPE=Release
  - cmake --build . --config Release
  - ctest -C Release